### ISSUE TITLE
Mermaid diagrams seem to be unable to render.

### ISSUE THREAD

**Issue by ruibaby** [xinkeng0/plugin-text-diagram#4] opened 2024-01-12 05:53 UTC
<img width="1663" alt="图片" src="https://github.com/halo-sigs/plugin-text-diagram/assets/21301288/7fa4ba73-24c9-4cbd-8832-0a27ff35ca49">
<img width="1485" alt="图片" src="https://github.com/halo-sigs/plugin-text-diagram/assets/21301288/bbb9f0bc-201c-4265-8979-bec87e244127">

**Comment by xinkeng0** [comment] 2024-01-12 06:05
I messed up mermaid's CSS selectot while changing the tags to comply with HTML standards.(`data-*` )
Would you mind change the CSS selector for mermaid to `text-diagram[data-type=mermaid]` and try it out.

**Comment by ruibaby** [comment] 2024-01-12 06:29
<img width="1458" alt="图片" src="https://github.com/halo-sigs/plugin-text-diagram/assets/21301288/6992b8ae-cc1e-479e-9021-139ba331ebf2">

**Comment by xinkeng0** [comment] 2024-01-12 06:55
It seems to be due to a problem with the Dom structure, and I will fix it.

**Comment by xinkeng0** [comment] 2024-01-12 07:01
To be honest, I overlooked mermaid because I focused on implementing PlantUML and introduced some regression bugs

**Comment by xinkeng0** [comment] 2024-01-15 09:08
Fixed in v1.1.0

**Closed as completed by xinkeng0** 2024-01-15 09:08 UTC
